/**
 * 
 */
package ar.com.nybble.futbol;



/**
 * @author notarip
 *
 */

public enum TipoDeLesion {FRACTURA_PERONE, FRACTURA_METATARSIANO, TENDINITIS_POPLÍTEA,
	TENDINITIS_AQUÍLEA, DOLOR_FEMORORROTULIANO, DISTENSIÓN_FEMORAL_POSTERIOR,
	SÍNDROME_PIRIFORME, ESGUINCE_LUMBAR, EPICONDILITIS_LATERAL, EPICONDILITIS_MEDIAL,
	TENDINITIS_DEL_MANGUITO_ROTADORES, ESGUINCES_TOBILLO, SÍNDROME_ESPOLÓN_CALCÁNEO,
	EPIFISITIS_DEL_CALCÁNEO, BURSITIS_POSTERIOR_TENDÓN_AQUILES, NEURALGIA_NERVIO_TIBIAL_POSTERIOR,
	HALLUX_RIGIDUS, DOLOR_NERVIO_INTERDIGITAL  

}
