/**
 * 
 */
package ar.com.nybble.futbol;



/**
 * @author notarip
 *
 */

public enum TipoDeLesion {FRACTURA_PERONE, FRACTURA_METATARSIANO, TENDINITIS_POPLOTEA,
	TENDINITIS_AQUILEA, DOLOR_FEMORORROTULIANO, DISTENSION_FEMORAL_POSTERIOR,
	SINDROME_PIRIFORME, ESGUINCE_LUMBAR, EPICONDILITIS_LATERAL, EPICONDILITIS_MEDIAL,
	TENDINITIS_DEL_MANGUITO_ROTADORES, ESGUINCES_TOBILLO, SINDROME_ESPOLON_CALCENEO,
	EPIFISITIS_DEL_CALCANEO, BURSITIS_POSTERIOR_TENDON_AQUILES, NEURALGIA_NERVIO_TIBIAL_POSTERIOR,
	HALLUX_RIGIDUS, DOLOR_NERVIO_INTERDIGITAL  

}
